# Generated by Django 4.2.4 on 2023-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_rename_certificate_endusercertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediateCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.IntegerField(
                        choices=[(0, "User"), (1, "Moderator"), (2, "Official")]
                    ),
                ),
                ("certificate_string", models.TextField()),
                ("private_key_string", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
