# Generated by Django 4.2.4 on 2023-08-04 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_intermediatecertificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intermediatecertificate",
            old_name="certificate_type",
            new_name="intermediate_type",
        ),
    ]
