# Generated by Django 4.2.4 on 2023-08-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "identity",
            "0004_rename_certificate_type_intermediatecertificate_intermediate_type",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="intermediatecertificate",
            old_name="intermediate_type",
            new_name="type",
        ),
        migrations.AddField(
            model_name="certificatesigningrequest",
            name="type",
            field=models.IntegerField(
                choices=[(0, "User"), (1, "Moderator"), (2, "Official")],
                default=None,
                null=True,
            ),
        ),
    ]
