stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - mv ~/backend/db.sqlite3 ~/db.sqlite3
    - rm -rf ~/backend
    - mkdir ~/backend
    - cp -r backend/* ~/backend
    - mv ~/db.sqlite3 ~/backend/db.sqlite3
    - cd ~/backend
    - python3 -m venv venv
    - source venv/bin/activate 
    - pip install --upgrade pip
    - pip install pip-tools
    - pip-sync
    - python manage.py migrate
    - python manage.py collectstatic --noinput 
  tags:
    - linux
    - prod
