# Generated by Django 4.2.4 on 2023-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.AddField(
            model_name="message",
            name="certificate",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
