# Generated by Django 4.2.4 on 2023-09-04 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_remove_message_author_message_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
