# Generated by Django 4.2.4 on 2023-09-04 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
