# Generated by Django 4.2.4 on 2023-09-05 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0005_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="signature",
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name="OfficialMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("sent", models.DateTimeField(auto_now_add=True)),
                ("signature", models.CharField(max_length=1024)),
                ("certificate", models.TextField()),
                ("locations", models.ManyToManyField(to="messaging.location")),
            ],
        ),
    ]
