# Generated by Django 4.2.3 on 2023-07-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0002_alter_certificatesigningrequest_csr_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("certificate_string", models.TextField()),
                (
                    "csr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificates.certificatesigningrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificates.applicationuser",
                    ),
                ),
            ],
        ),
    ]
