# Generated by Django 4.2.3 on 2023-07-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0003_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="csr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cert",
                to="certificates.certificatesigningrequest",
            ),
        ),
        migrations.AlterField(
            model_name="certificatesigningrequest",
            name="status",
            field=models.IntegerField(
                choices=[(0, "New"), (1, "Approved"), (-1, "Denied")], default=0
            ),
        ),
    ]
