# Generated by Django 4.2.3 on 2023-07-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0004_alter_certificate_csr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="id",
        ),
        migrations.AlterField(
            model_name="certificate",
            name="csr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="cert",
                serialize=False,
                to="certificates.certificatesigningrequest",
            ),
        ),
    ]
