# Generated by Django 4.2.3 on 2023-08-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0005_remove_certificate_id_alter_certificate_csr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_string",
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="csr",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="cert",
                serialize=False,
                to="certificates.certificatesigningrequest",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="certificates.applicationuser",
            ),
        ),
    ]
